GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2VsdmluIiwiaWF0IjoxNjkzMDgxMDE3fQ.PzaD12rsuIOlQbA5rhiUuzn8-QSBxpdMGHpnjFsK27k
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kelvin"
}